export type Mission = { id:string; category:string; title:string; status:string; priority:"Critical"|"High"|"Medium"|"Low"; next:string; due:string; days:number; waiting:string; notes:string; conversation?:string; context?:string; sourceUrl?:string; timelineEvents?:number };

export const missions: Mission[] = [
  {id:"CC-001",category:"Legal & Employment",title:"Prepare for solicitor consultation",status:"In progress",priority:"Critical",next:"Complete the paperwork and put the latest documents in one place.",due:"13 Jul",days:1,waiting:"Tolu",notes:"Consultation at 14:00.",conversation:"Helen Moss, Lucy Stones & Terrie Massingham | Lincs Law",context:"Consultation, engagement letter, ID and latest agreement.",sourceUrl:"https://mail.google.com/mail/#all/19f4b4b8efffd6bf",timelineEvents:1},
  {id:"CC-002",category:"Legal & Employment",title:"Settlement decision deadline",status:"In progress",priority:"Critical",next:"Complete the legal review and make the final decision.",due:"15 Jul",days:3,waiting:"Tolu / solicitor",notes:"Deadline at 17:00.",conversation:"Niamh Kelly | The HR Dept, for Igloo Vision",sourceUrl:"https://mail.google.com/mail/#all/19f3e0b698658096",timelineEvents:1},
  {id:"CC-003",category:"Finance & Debt",title:"Contact ACI about visit notice",status:"Not started",priority:"Critical",next:"Request a hold and propose an affordable payment arrangement.",due:"13 Jul",days:1,waiting:"Tolu",notes:"Keep a written record of any arrangement.",conversation:"ACI UK / Verify | Lendable account",sourceUrl:"https://mail.google.com/mail/#all/19f4d00cd1d71402",timelineEvents:1},
  {id:"CC-004",category:"Health",title:"Physiotherapy appeal follow-up",status:"Waiting",priority:"High",next:"Follow up if no update has arrived.",due:"17 Jul",days:5,waiting:"Hospital team",notes:"Appeal requested; outcome pending.",conversation:"Gary Walker | St George's Maxillofacial",sourceUrl:"https://mail.google.com/mail/#all/19f45ee8a21578c5",timelineEvents:1},
  {id:"CC-005",category:"Complaints",title:"Check compensation payment",status:"Waiting",priority:"Medium",next:"Verify that the payment has arrived.",due:"20 Jul",days:8,waiting:"Bank complaints team",notes:"Expected within 5–7 working days.",conversation:"Nationwide Complaints Team",sourceUrl:"https://mail.google.com/mail/#all/19f476b83b08f4a8",timelineEvents:1},
  {id:"CC-006",category:"Bills",title:"Confirm mobile payment plan",status:"In progress",priority:"High",next:"Check the current plan and make the next required payment.",due:"31 Jul",days:19,waiting:"Tolu / provider",notes:"Verify the latest balance.",conversation:"O2 Billing & Collections",sourceUrl:"https://mail.google.com/mail/#all/19f3c183bbc678e3",timelineEvents:1},
  {id:"CC-007",category:"Complaints",title:"Complaint final-response window",status:"Waiting",priority:"Medium",next:"Chase if no final response has arrived.",due:"18 Aug",days:37,waiting:"Complaint handler",notes:"Approximate eight-week response date.",conversation:"Clearpay Support Complaints Team",sourceUrl:"https://mail.google.com/mail/#all/19f51e96861b227e",timelineEvents:1},
  {id:"CC-008",category:"Housing",title:"Prepare for possession hearing",status:"In progress",priority:"Critical",next:"Confirm court details and organise payment evidence.",due:"2 Sep",days:52,waiting:"Tolu / adviser",notes:"Hearing at 11:00; venue needs confirmation.",conversation:"Isabell Edwards-Adamson | Greenhalgh Kerr",sourceUrl:"https://mail.google.com/mail/#all/19edf2b113536cb6",timelineEvents:1},
  {id:"CC-009",category:"Housing",title:"Resolve July rent issue",status:"Needs review",priority:"Critical",next:"Review payment records and respond with evidence.",due:"13 Jul",days:1,waiting:"Tolu",notes:"Rent was stated as due on 1 July.",conversation:"Lerayne Nisbett | Folio London",sourceUrl:"https://mail.google.com/mail/#all/19f377d18ee1e5aa",timelineEvents:1},
  {id:"CC-010",category:"Complaints",title:"Ombudsman referral deadline",status:"Not started",priority:"Low",next:"Escalate only if dissatisfied and still unresolved.",due:"9 Jan 2027",days:181,waiting:"Tolu",notes:"Six months from the decision date.",conversation:"Nationwide Complaints Team",sourceUrl:"https://mail.google.com/mail/#all/19f476b83b08f4a8",timelineEvents:1}
  ,{id:"CC-011",category:"Housing",title:"Confirm immediate housing and moving plan",status:"Needs review",priority:"High",next:"Confirm where you will stay, move timing, storage and keys.",due:"17 Jul",days:5,waiting:"Tolu / family",notes:"Mum and Toro discussed the next place and practical moving support.",conversation:"Mum and Toro",sourceUrl:"https://drive.google.com/file/d/1NiCi6tMNAFzYH59ATB7f1nu_rUWQZzNV/view",timelineEvents:2}
  ,{id:"CC-012",category:"Security",title:"Confirm recent account-access changes",status:"Needs review",priority:"Critical",next:"Confirm Equifax, email migration and OpenAI account changes were expected.",due:"12 Jul",days:0,waiting:"Tolu",notes:"Secure any account showing unrecognised activity.",conversation:"Equifax, Google, Yahoo and OpenAI",sourceUrl:"https://mail.google.com/mail/#all/19f54ec7edafcd8b",timelineEvents:3}
];

export const events = [
  ["MON 13", "09:00", "Urgent finance call", "CRITICAL"], ["MON 13", "14:00", "Solicitor consultation", "CRITICAL"],
  ["WED 15", "17:00", "Settlement decision", "CRITICAL"], ["FRI 17", "13:00", "Physio appeal check", "HIGH"],
  ["MON 20", "09:00", "Verify compensation", "MEDIUM"], ["FRI 31", "09:00", "Mobile payment check", "HIGH"]
];
